### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by Zalazim** [kelvinthh/ig-dm-reels-autodownload#1]
Hello,
I am trying to install the required packages, but the adress for it is wrong.
How could I fix that ?
Thank you !

`ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\runner\\miniforge3\\conda-bld\\black-recipe_1682492095737\\work'`

**Comment by kelvinthh** [comment]
Pull from the main branch again and do a `pip install -r requirements.txt`, I incidentally included some conda env stuff into the previous requirements.txt, should be fixed now.

**Comment by Zalazim** [comment]
Hello,
Thank you for your answer. I managed to got over it. I worked a bit on this, and now I have [another issue](https://github.com/kelvinthh/ig-dm-reels-autodownload/issues/2).
